# Generated by Django 3.2.12 on 2022-05-11 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='articulo',
            field=models.TextField(max_length=180),
        ),
    ]
