# Generated by Django 3.2.12 on 2022-05-11 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_noticia_articulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='articulo',
            field=models.TextField(max_length=500),
        ),
    ]
