# Generated by Django 3.2.12 on 2022-05-11 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_noticia_articulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='titulo',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
