# Generated by Django 3.2.12 on 2022-05-11 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_noticia_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='imagen',
            field=models.ImageField(default=1, upload_to='imagen_home'),
            preserve_default=False,
        ),
    ]
