# Generated by Django 3.2.12 on 2022-05-11 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_home'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='titulo',
            field=models.CharField(max_length=30, verbose_name='Titulo pagina'),
        ),
    ]
