# Generated by Django 3.2.12 on 2022-03-03 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pqr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('mail', models.EmailField(max_length=254)),
                ('ciudad', models.CharField(max_length=40)),
                ('empresa', models.CharField(max_length=60)),
                ('telefono', models.CharField(max_length=15)),
                ('aceptar', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='pqr',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
