# Generated by Django 3.2.12 on 2022-03-17 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pqr', '0002_auto_20220303_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='pqr',
            name='ciudad_env',
            field=models.CharField(default=1, max_length=80, verbose_name='Ciudad envio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pqr',
            name='ciudad_radi',
            field=models.CharField(default=1, max_length=80, verbose_name='Ciudad radicado'),
            preserve_default=False,
        ),
    ]
