# Generated by Django 3.2.12 on 2022-03-26 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pqr', '0007_auto_20220324_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='pqr',
            name='archivo',
            field=models.FileField(default=1, upload_to='archivos_pqr'),
            preserve_default=False,
        ),
    ]
