# Generated by Django 3.2.12 on 2022-03-26 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pqr', '0008_pqr_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pqr',
            name='archivo',
            field=models.FileField(blank=True, upload_to='archivos_pqr'),
        ),
    ]
