# Generated by Django 3.2.12 on 2022-04-07 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pqr', '0009_alter_pqr_archivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pqr.pqr')),
                ('tipo', models.CharField(max_length=2)),
                ('respuesta', models.CharField(max_length=7500)),
            ],
        ),
    ]
