# Generated by Django 3.2.12 on 2022-04-07 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pqr', '0010_respuesta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuesta',
            name='tipo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otros')], max_length=2),
        ),
    ]
