# Generated by Django 3.2.12 on 2022-04-08 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pqr', '0014_respuesta_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuesta',
            name='id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pqr.pqr', verbose_name='numero_pqr'),
        ),
    ]
