# Generated by Django 3.2.12 on 2022-04-08 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pqr', '0015_alter_respuesta_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuesta',
            name='id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='pqr_respuesta', serialize=False, to='pqr.pqr', verbose_name='numero_pqr'),
        ),
    ]
