# Generated by Django 3.2.12 on 2022-06-10 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pqr', '0018_alter_respuesta_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='observacion',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
