# Generated by Django 3.2.5 on 2022-06-13 17:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pqr', '0020_alter_contacto_observacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
